---
# Deploy Tomcat
- import_playbook: jdk.yml
- hosts: webservers
  vars:
    tomcat_host: 127.0.0.1
    tomcat_port: 8080
    tomcat_download_url: http://www-us.apache.org/dist/tomcat/tomcat-8/v8.5.29/bin/apache-tomcat-8.5.29.tar.gz
  remote_user: ubuntu
  become: true
  become_method: sudo
  tasks:
  - name: add group "tomcat"
    group: name=tomcat

  - name: add user "tomcat"
    user: name=tomcat group=tomcat home=/usr/share/tomcat createhome=no

  - name: add directory /opt/tomcat
    file:
      path: /opt/tomcat
      state: directory
      mode: 0755

  - name: download and unpack tomcat
    unarchive:
      src: "{{ tomcat_download_url }}"
      dest: /opt/tomcat
      extra_opts: [--strip-components=1]
      remote_src: yes

  - name: change ownership of Tomcat installation
    file:
      path: /opt/tomcat/
      owner: tomcat
      group: tomcat
      state: directory
      mode: 0755
      recurse: yes

  - name: update server.xml.j2
    template:
      src: files/server.xml.j2
      dest: /opt/tomcat/conf/
    notify: start tomcat

#  - name: wait for tomcat to start
#    wait_for:
#      host: "{{ tomcat_host }}"
#      port: "{{ tomcat_port }}"

  handlers:
  - name: start tomcat
    script: /opt/tomcat/bin/startup.sh
    remote_user: tomcat
    become: true
    become_method: sudo