---
- name: create groups
  group: name=webapps state=present
  with_items:
    - tomcat
    - webapps
  become: true
  become_user: root

- name: create user "tomcat"
  user: name=tomcat groups=tomcat,webapps home={{ tomcat_path }} createhome=no
  become: true
  become_user: root

- name: create tomcat folders
  file: path={{ item.path }} state=directory mode={{ item.mode }} owner=tomcat group=tomcat
  with_items:
    - { path: "/opt/apache-tomcat-{{ tomcat_version }}",  mode: '750', owner: 'tomcat', group: 'tomcat' }
    - { path: "/var/run/tomcat",  mode: '750', owner: 'tomcat', group: 'tomcat' }
  become: true
  become_user: root

- name: create symlink to the current tomcat version
  file: src=/opt/apache-tomcat-{{ tomcat_version }} dest={{ tomcat_path }} state=link group=tomcat owner=tomcat mode=770
  become: true
  become_user: root

- name: copy tar.gz with tomcat
  copy: src=files/apache-tomcat-{{ tomcat_version }}.tar.gz dest=/tmp force=no

- name: extract tar.gz into /opt
  unarchive: src=/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz dest=/opt owner=tomcat group=tomcat mode=770 remote_src=yes
  become: true
  become_user: tomcat

- name: add tomcat to systemd
  template: src=templates/tomcat.service.j2 dest=/etc/systemd/system/tomcat.service
  become: true
  become_user: root

- name: enable tomcat service
  systemd: name=tomcat enabled=yes daemon_reload=yes
  become: true
  become_user: root