---
- name: stop service tomcat
  systemd: name=tomcat state=stopped
  become: true
  become_user: root

- name: copy myapp.war
  copy: src=files/myapp.war dest={{ webapp_path }} owner={{ webapp_owner }} group={{ webapp_group }} mode=550
  become: true
  become_user: root

- name: start service tomcat
  systemd: name=tomcat state=started
  become: true
  become_user: root