---
# Install oracle jdk
- hosts: webservers
  vars:
    tomcat_host: 127.0.0.1
    tomcat_port: 8080
  remote_user: ubuntu
  become: true
  become_method: sudo
  tasks:
  - name: Install ppt-repository for oracle-jdk 8
    apt_repository: repo='ppa:webupd8team/java'

  - name: Auto accept oracle jdk license
    shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections

  - name: Install oracle-jdk 8
    apt:
      name: oracle-java8-installer
      state: installed
      update_cache: true