---
# Deploys nginx
- hosts: webservers
  vars:
    nginx_host: 0.0.0.0
    nginx_port: 80
    proxy_path: http://127.0.0.1:8080
    proxy_static_path: /opt/tomcat/webapps/ROOT
  remote_user: ubuntu
  become: true
  become_method: sudo
  tasks:
  - name: install nginx
    apt: pkg=nginx state=installed update_cache=true
    notify: start nginx

  - name: configure nginx as tomcat proxy
    template:
      src: files/nginx.conf
      dest: /etc/nginx/sites-available
    notify: restart nginx

  - name: clean all sites enabled
    file:
      path: /etc/nginx/sites-enabled/
      state: absent

  - name: add directory /etc/nginx/sites-enabled/
    file:
      path: /etc/nginx/sites-enabled/
      state: directory

  - name: add symlink to configuration
    file:
      src: "/etc/nginx/sites-available/nginx.conf"
      dest: "/etc/nginx/sites-enabled/nginx.conf"
      state: link
    notify: restart nginx

  handlers:
  - name: start nginx
    service: name=nginx state=started

  - name: restart nginx
    service: name=nginx state=restarted enabled=yes